/* These adjectives are used in the footer: 'A ${random adj} RCOS project!' */
export default [
  'lazy',
  'open-source',
  'somewhat interesting',
  'spicy',
  'Shirley-approved',
  'out of control',
  'expensive',
  'better-than-WPI',
  'tactful',
  'honest',
  'magical',
  'territorial',
  'easter-egged',
  'loyal',
  'gentle',
  'agreeable',
  'big',
  'calm',
  'energetic',
  'enthusiastic',
  'determined',
  'good-natured',
  'eager',
  'late',
  'early',
  'strange',
  'uncomfy',
  'moist',
  'dank',
  'zany',
  'squishy',
  'exquisite',
  'large'
]
